# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.shop::lang.categories.model

# Model Form Field configuration
form: $/bedard/shop/models/category/fields.yaml

# Model Class name
modelClass: Bedard\Shop\Models\Category

# Default redirect location
defaultRedirect: bedard/shop/categories

# Create page
create:
    title: backend::lang.relation.create_name
    redirect: bedard/shop/categories/update/:id
    redirectClose: bedard/shop/categories

# Update page
update:
    title: backend::lang.relation.update_name
    redirect: bedard/shop/categories
    redirectClose: bedard/shop/categories

# Preview page
preview:
    title: backend::lang.relations.preview_name
