# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        label: bedard.shop::lang.categories.controller
        modelClass: Bedard\Shop\Models\Category
        nameFrom: name
        scope: filterByCategory
