# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.shop::lang.products.model

# Model Form Field configuration
form: $/bedard/shop/models/product/fields.yaml

# Model Class name
modelClass: Bedard\Shop\Models\Product

# Default redirect location
defaultRedirect: bedard/shop/products

# Create page
create:
    title: backend::lang.relation.create_name
    redirect: bedard/shop/products/update/:id
    redirectClose: bedard/shop/products

# Update page
update:
    title: backend::lang.relation.update_name
    redirect: bedard/shop/products
    redirectClose: bedard/shop/products

# Preview page
preview:
    title: backend::lang.relations.preview_name
