# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        label: bedard.shop::lang.categories.controller
        modelClass: Bedard\Shop\Models\Category
        nameFrom: name
        scope: filterByCategory

    is_enabled:
        label: bedard.shop::lang.products.filter_disabled
        type: checkbox
        scope: isEnabled

    in_stock:
        label: bedard.shop::lang.products.filter_out_of_stock
        type: checkbox
        scope: inStock
