# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status:
        label: bedard.shop::lang.discounts.hide_expired
        type: checkbox
        scope: isActiveOrUpcoming
