# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.shop::lang.customers.model

# Model Form Field configuration
form: $/bedard/shop/models/customer/fields.yaml

# Model Class name
modelClass: Bedard\Shop\Models\Customer

# Default redirect location
defaultRedirect: bedard/shop/customers

# Create page
create:
    title: backend::lang.relation.create_name
    redirect: bedard/shop/customers/update/:id
    redirectClose: bedard/shop/customers

# Update page
update:
    title: backend::lang.relation.update_name
    redirect: bedard/shop/customers
    redirectClose: bedard/shop/customers

# Preview page
preview:
    title: backend::lang.relations.preview_name
