# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status:
        label: bedard.shop::lang.orders.filter_label
        modelClass: Bedard\Shop\Models\Status
        nameFrom: name
        scope: filterByStatus
